### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dnkls** [zanyarjamal/zambie#1]
I got this error : 

Traceback (most recent call last):
  File "./zambie.py", line 263, in <module>
    subprocess.call(["./Dos_Attacks/DNS/dnsscan", class_a_start, class_a_end, outfile_dns, threads_dns,scan_delay_ms_DNS]) #---> DNS
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Armanmd** [comment]
same problem

**Comment by AmrSK** [comment]
same

**Comment by kellogs43** [comment]
To me the sudo command says : sudo : leafpad/etc/apt/sources.list : command not found

**Comment by baran1231** [comment]
u dont need sudo

**Comment by baran1231** [comment]
this didnt work for me
idk why

**Comment by F8TL** [comment]
Is there another solution i tried this and i still get the same error... Please help

**Comment by CRUC14L** [comment]
It didn't work because you might have put "leafpad/etc/apt/sources.list". You are suppose to put
"leafpad /etc/apt/sources.list". You need to have leafpad installed. If you dont replace "leafpad" for some kind of notepad.
To fix the issue im going to go in detail.

Step 1: Open Terminal and make sure you are in the the root dir. (type cd to go there)
Step 2: Type "(notepad application here) /etc/apt/sources.list"
Step 3: It should open up a notepad with the text file of sources.list
Step 4: Delete everything you see in the list file.
Step 5: Copy and Past "deb http://old.kali.org/kali sana main non-free contrib" into it
Step 5: Save the list by hitting Ctrl+S or going to "File" then Click "Save"
Step 6: Update your OS by typing " apt-get update"
